FROM --platform=$BUILDPLATFORM docker.io/rust:bookworm

RUN apt update
RUN apt install -y python3 python3-dev python3-pip
RUN python3 -m pip install pdm --break-system-packages

# For x86_64 (64-bit)
RUN rustup target add x86_64-unknown-linux-musl

# For ARM64 (e.g. Raspberry Pi 4, Apple M1)
RUN rustup target add aarch64-unknown-linux-musl

# For ARMv7 (e.g. Raspberry Pi 3 with 32-bit OS)
RUN rustup target add armv7-unknown-linux-musleabihf

# For 32-bit x86
RUN rustup target add i686-unknown-linux-musl
