FROM --platform=$BUILDPLATFORM ghcr.io/rust-cross/rust-musl-cross:x86_64-musl AS builder-amd64

FROM --platform=$BUILDPLATFORM ghcr.io/rust-cross/rust-musl-cross:i686-musl AS builder-386

FROM --platform=$BUILDPLATFORM ghcr.io/rust-cross/rust-musl-cross:aarch64-musl AS builder-aarch64

FROM --platform=$BUILDPLATFORM	ghcr.io/rust-cross/rust-musl-cross:armv7-musleabi AS builder-armv7

FROM --platform=$BUILDPLATFORM ghcr.io/rust-cross/rust-musl-cross:s390x-musl AS builder-s390x

FROM --platform=$BUILDPLATFORM ghcr.io/rust-cross/rust-musl-cross:powerpc64le-musl AS builder-ppc64le

ARG BUILDARCH

FROM builder-$BUILDARCH AS builder

RUN apt update

RUN apt install python3 python3-dev python3-pip -y
RUN pip install pdm
