name: Docs

on:
  pull_request:
  branches:
    - main
  tags:
    - "*.*.*"
    - "v*.*.*"

jobs:
  build-docs:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
          fetch-depth: 0
          sparse-checkout: |
            docs
            pdm.lock
            pyproject.toml
            mkdocs.yml
