name: Run integration tests

env:
  CARGO_HOME: ${{ github.workspace }}/.c

on:
  schedule:
    - cron: "* 5 * * *"
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
    name: Integration test
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        os: ["windows-2025", "ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo vendor
        run: cargo vendor
      - name: Install dependencies
        run: pdm install --frozen-lock
      - name: Run pytest
        env:
          FLAY_INTEGRATION_TEST: 1
        run: pdm run pytest
